// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "addRoundKey4.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic addRoundKey4::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic addRoundKey4::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> addRoundKey4::ap_ST_fsm_state1 = "1";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state2 = "10";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state3 = "100";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state4 = "1000";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state5 = "10000";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state6 = "100000";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> addRoundKey4::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> addRoundKey4::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> addRoundKey4::ap_const_lv32_1 = "1";
const sc_lv<32> addRoundKey4::ap_const_lv32_8 = "1000";
const sc_lv<32> addRoundKey4::ap_const_lv32_2 = "10";
const sc_lv<32> addRoundKey4::ap_const_lv32_3 = "11";
const sc_lv<32> addRoundKey4::ap_const_lv32_4 = "100";
const sc_lv<32> addRoundKey4::ap_const_lv32_5 = "101";
const sc_lv<32> addRoundKey4::ap_const_lv32_6 = "110";
const sc_lv<32> addRoundKey4::ap_const_lv32_7 = "111";
const sc_lv<32> addRoundKey4::ap_const_lv32_9 = "1001";
const sc_lv<32> addRoundKey4::ap_const_lv32_A = "1010";
const sc_lv<32> addRoundKey4::ap_const_lv32_B = "1011";
const sc_lv<32> addRoundKey4::ap_const_lv32_C = "1100";
const sc_lv<32> addRoundKey4::ap_const_lv32_D = "1101";
const sc_lv<32> addRoundKey4::ap_const_lv32_E = "1110";
const sc_lv<64> addRoundKey4::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> addRoundKey4::ap_const_lv64_1 = "1";
const sc_lv<64> addRoundKey4::ap_const_lv64_2 = "10";
const sc_lv<64> addRoundKey4::ap_const_lv64_3 = "11";
const sc_lv<64> addRoundKey4::ap_const_lv64_4 = "100";
const sc_lv<64> addRoundKey4::ap_const_lv64_5 = "101";
const sc_lv<64> addRoundKey4::ap_const_lv64_6 = "110";
const sc_lv<64> addRoundKey4::ap_const_lv64_7 = "111";
const sc_lv<64> addRoundKey4::ap_const_lv64_8 = "1000";
const sc_lv<64> addRoundKey4::ap_const_lv64_9 = "1001";
const sc_lv<64> addRoundKey4::ap_const_lv64_A = "1010";
const sc_lv<64> addRoundKey4::ap_const_lv64_B = "1011";
const sc_lv<64> addRoundKey4::ap_const_lv64_C = "1100";
const sc_lv<64> addRoundKey4::ap_const_lv64_D = "1101";
const sc_lv<64> addRoundKey4::ap_const_lv64_E = "1110";
const sc_lv<64> addRoundKey4::ap_const_lv64_F = "1111";
const sc_lv<32> addRoundKey4::ap_const_lv32_F = "1111";
const bool addRoundKey4::ap_const_boolean_1 = true;

addRoundKey4::addRoundKey4(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_grp_fu_346_p2);
    sensitive << ( roundKey_data_V_q0 );
    sensitive << ( reg_338 );

    SC_METHOD(thread_grp_fu_353_p2);
    sensitive << ( roundKey_data_V_q1 );
    sensitive << ( reg_342 );

    SC_METHOD(thread_op2_V_read_assign_28_fu_360_p2);
    sensitive << ( roundKey_data_V_q0 );
    sensitive << ( state_data_V_load_47_reg_462 );

    SC_METHOD(thread_op2_V_read_assign_29_fu_366_p2);
    sensitive << ( roundKey_data_V_q1 );
    sensitive << ( state_data_V_load_48_reg_467 );

    SC_METHOD(thread_op2_V_read_assign_30_fu_372_p2);
    sensitive << ( roundKey_data_V_q0 );
    sensitive << ( state_data_V_load_49_reg_482 );

    SC_METHOD(thread_op2_V_read_assign_31_fu_378_p2);
    sensitive << ( roundKey_data_V_q1 );
    sensitive << ( state_data_V_load_50_reg_487 );

    SC_METHOD(thread_op2_V_read_assign_32_fu_384_p2);
    sensitive << ( roundKey_data_V_q0 );
    sensitive << ( state_data_V_load_51_reg_502 );

    SC_METHOD(thread_op2_V_read_assign_33_fu_390_p2);
    sensitive << ( roundKey_data_V_q1 );
    sensitive << ( state_data_V_load_52_reg_507 );

    SC_METHOD(thread_op2_V_read_assign_34_fu_396_p2);
    sensitive << ( roundKey_data_V_q0 );
    sensitive << ( state_data_V_load_53_reg_522 );

    SC_METHOD(thread_op2_V_read_assign_35_fu_402_p2);
    sensitive << ( roundKey_data_V_q1 );
    sensitive << ( state_data_V_load_54_reg_527 );

    SC_METHOD(thread_op2_V_read_assign_36_fu_408_p2);
    sensitive << ( roundKey_data_V_q0 );
    sensitive << ( state_data_V_load_55_reg_542 );

    SC_METHOD(thread_op2_V_read_assign_37_fu_414_p2);
    sensitive << ( roundKey_data_V_q1 );
    sensitive << ( state_data_V_load_56_reg_547 );

    SC_METHOD(thread_op2_V_read_assign_38_fu_420_p2);
    sensitive << ( roundKey_data_V_q0 );
    sensitive << ( state_data_V_load_57_reg_572 );

    SC_METHOD(thread_op2_V_read_assign_39_fu_426_p2);
    sensitive << ( roundKey_data_V_q1 );
    sensitive << ( state_data_V_load_58_reg_577 );

    SC_METHOD(thread_roundKey_data_V_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_roundKey_data_V_address1);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_roundKey_data_V_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_roundKey_data_V_ce1);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_state_data_V_addr_46_reg_437);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_state_data_V_addr_47_reg_442);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_state_data_V_addr_48_reg_447);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_state_data_V_addr_49_reg_452);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_state_data_V_addr_50_reg_457);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_state_data_V_addr_51_reg_472);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_state_data_V_addr_52_reg_477);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_state_data_V_addr_53_reg_492);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_state_data_V_addr_54_reg_497);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_state_data_V_addr_55_reg_512);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_state_data_V_addr_56_reg_517);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_state_data_V_addr_57_reg_532);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_state_data_V_addr_58_reg_537);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_state_data_V_addr_59_reg_552);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_state_data_V_addr_60_reg_557);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_state_data_V_addr_reg_432);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_state_data_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( state_data_V_addr_reg_432 );
    sensitive << ( state_data_V_addr_47_reg_442 );
    sensitive << ( state_data_V_addr_49_reg_452 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( state_data_V_addr_51_reg_472 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( state_data_V_addr_53_reg_492 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( state_data_V_addr_55_reg_512 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( state_data_V_addr_57_reg_532 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( state_data_V_addr_59_reg_552 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_address1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( state_data_V_addr_46_reg_437 );
    sensitive << ( state_data_V_addr_48_reg_447 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( state_data_V_addr_50_reg_457 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( state_data_V_addr_52_reg_477 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( state_data_V_addr_54_reg_497 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( state_data_V_addr_56_reg_517 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( state_data_V_addr_58_reg_537 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( state_data_V_addr_60_reg_557 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_d0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( grp_fu_346_p2 );
    sensitive << ( op2_V_read_assign_28_fu_360_p2 );
    sensitive << ( op2_V_read_assign_30_fu_372_p2 );
    sensitive << ( op2_V_read_assign_32_fu_384_p2 );
    sensitive << ( op2_V_read_assign_34_fu_396_p2 );
    sensitive << ( op2_V_read_assign_36_fu_408_p2 );
    sensitive << ( op2_V_read_assign_38_fu_420_p2 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_d1);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( grp_fu_353_p2 );
    sensitive << ( op2_V_read_assign_29_fu_366_p2 );
    sensitive << ( op2_V_read_assign_31_fu_378_p2 );
    sensitive << ( op2_V_read_assign_33_fu_390_p2 );
    sensitive << ( op2_V_read_assign_35_fu_402_p2 );
    sensitive << ( op2_V_read_assign_37_fu_414_p2 );
    sensitive << ( op2_V_read_assign_39_fu_426_p2 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_we0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_we1);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    ap_CS_fsm = "0000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "addRoundKey4_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, state_data_V_address0, "(port)state_data_V_address0");
    sc_trace(mVcdFile, state_data_V_ce0, "(port)state_data_V_ce0");
    sc_trace(mVcdFile, state_data_V_we0, "(port)state_data_V_we0");
    sc_trace(mVcdFile, state_data_V_d0, "(port)state_data_V_d0");
    sc_trace(mVcdFile, state_data_V_q0, "(port)state_data_V_q0");
    sc_trace(mVcdFile, state_data_V_address1, "(port)state_data_V_address1");
    sc_trace(mVcdFile, state_data_V_ce1, "(port)state_data_V_ce1");
    sc_trace(mVcdFile, state_data_V_we1, "(port)state_data_V_we1");
    sc_trace(mVcdFile, state_data_V_d1, "(port)state_data_V_d1");
    sc_trace(mVcdFile, state_data_V_q1, "(port)state_data_V_q1");
    sc_trace(mVcdFile, roundKey_data_V_address0, "(port)roundKey_data_V_address0");
    sc_trace(mVcdFile, roundKey_data_V_ce0, "(port)roundKey_data_V_ce0");
    sc_trace(mVcdFile, roundKey_data_V_q0, "(port)roundKey_data_V_q0");
    sc_trace(mVcdFile, roundKey_data_V_address1, "(port)roundKey_data_V_address1");
    sc_trace(mVcdFile, roundKey_data_V_ce1, "(port)roundKey_data_V_ce1");
    sc_trace(mVcdFile, roundKey_data_V_q1, "(port)roundKey_data_V_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, reg_338, "reg_338");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, reg_342, "reg_342");
    sc_trace(mVcdFile, state_data_V_addr_reg_432, "state_data_V_addr_reg_432");
    sc_trace(mVcdFile, state_data_V_addr_46_reg_437, "state_data_V_addr_46_reg_437");
    sc_trace(mVcdFile, state_data_V_addr_47_reg_442, "state_data_V_addr_47_reg_442");
    sc_trace(mVcdFile, state_data_V_addr_48_reg_447, "state_data_V_addr_48_reg_447");
    sc_trace(mVcdFile, state_data_V_addr_49_reg_452, "state_data_V_addr_49_reg_452");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, state_data_V_addr_50_reg_457, "state_data_V_addr_50_reg_457");
    sc_trace(mVcdFile, state_data_V_load_47_reg_462, "state_data_V_load_47_reg_462");
    sc_trace(mVcdFile, state_data_V_load_48_reg_467, "state_data_V_load_48_reg_467");
    sc_trace(mVcdFile, state_data_V_addr_51_reg_472, "state_data_V_addr_51_reg_472");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, state_data_V_addr_52_reg_477, "state_data_V_addr_52_reg_477");
    sc_trace(mVcdFile, state_data_V_load_49_reg_482, "state_data_V_load_49_reg_482");
    sc_trace(mVcdFile, state_data_V_load_50_reg_487, "state_data_V_load_50_reg_487");
    sc_trace(mVcdFile, state_data_V_addr_53_reg_492, "state_data_V_addr_53_reg_492");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, state_data_V_addr_54_reg_497, "state_data_V_addr_54_reg_497");
    sc_trace(mVcdFile, state_data_V_load_51_reg_502, "state_data_V_load_51_reg_502");
    sc_trace(mVcdFile, state_data_V_load_52_reg_507, "state_data_V_load_52_reg_507");
    sc_trace(mVcdFile, state_data_V_addr_55_reg_512, "state_data_V_addr_55_reg_512");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, state_data_V_addr_56_reg_517, "state_data_V_addr_56_reg_517");
    sc_trace(mVcdFile, state_data_V_load_53_reg_522, "state_data_V_load_53_reg_522");
    sc_trace(mVcdFile, state_data_V_load_54_reg_527, "state_data_V_load_54_reg_527");
    sc_trace(mVcdFile, state_data_V_addr_57_reg_532, "state_data_V_addr_57_reg_532");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, state_data_V_addr_58_reg_537, "state_data_V_addr_58_reg_537");
    sc_trace(mVcdFile, state_data_V_load_55_reg_542, "state_data_V_load_55_reg_542");
    sc_trace(mVcdFile, state_data_V_load_56_reg_547, "state_data_V_load_56_reg_547");
    sc_trace(mVcdFile, state_data_V_addr_59_reg_552, "state_data_V_addr_59_reg_552");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, state_data_V_addr_60_reg_557, "state_data_V_addr_60_reg_557");
    sc_trace(mVcdFile, state_data_V_load_57_reg_572, "state_data_V_load_57_reg_572");
    sc_trace(mVcdFile, state_data_V_load_58_reg_577, "state_data_V_load_58_reg_577");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, grp_fu_346_p2, "grp_fu_346_p2");
    sc_trace(mVcdFile, grp_fu_353_p2, "grp_fu_353_p2");
    sc_trace(mVcdFile, op2_V_read_assign_28_fu_360_p2, "op2_V_read_assign_28_fu_360_p2");
    sc_trace(mVcdFile, op2_V_read_assign_29_fu_366_p2, "op2_V_read_assign_29_fu_366_p2");
    sc_trace(mVcdFile, op2_V_read_assign_30_fu_372_p2, "op2_V_read_assign_30_fu_372_p2");
    sc_trace(mVcdFile, op2_V_read_assign_31_fu_378_p2, "op2_V_read_assign_31_fu_378_p2");
    sc_trace(mVcdFile, op2_V_read_assign_32_fu_384_p2, "op2_V_read_assign_32_fu_384_p2");
    sc_trace(mVcdFile, op2_V_read_assign_33_fu_390_p2, "op2_V_read_assign_33_fu_390_p2");
    sc_trace(mVcdFile, op2_V_read_assign_34_fu_396_p2, "op2_V_read_assign_34_fu_396_p2");
    sc_trace(mVcdFile, op2_V_read_assign_35_fu_402_p2, "op2_V_read_assign_35_fu_402_p2");
    sc_trace(mVcdFile, op2_V_read_assign_36_fu_408_p2, "op2_V_read_assign_36_fu_408_p2");
    sc_trace(mVcdFile, op2_V_read_assign_37_fu_414_p2, "op2_V_read_assign_37_fu_414_p2");
    sc_trace(mVcdFile, op2_V_read_assign_38_fu_420_p2, "op2_V_read_assign_38_fu_420_p2");
    sc_trace(mVcdFile, op2_V_read_assign_39_fu_426_p2, "op2_V_read_assign_39_fu_426_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

addRoundKey4::~addRoundKey4() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void addRoundKey4::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        reg_338 = state_data_V_q0.read();
        reg_342 = state_data_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        state_data_V_load_47_reg_462 = state_data_V_q0.read();
        state_data_V_load_48_reg_467 = state_data_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_data_V_load_49_reg_482 = state_data_V_q0.read();
        state_data_V_load_50_reg_487 = state_data_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        state_data_V_load_51_reg_502 = state_data_V_q0.read();
        state_data_V_load_52_reg_507 = state_data_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        state_data_V_load_53_reg_522 = state_data_V_q0.read();
        state_data_V_load_54_reg_527 = state_data_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_data_V_load_55_reg_542 = state_data_V_q0.read();
        state_data_V_load_56_reg_547 = state_data_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_data_V_load_57_reg_572 = state_data_V_q0.read();
        state_data_V_load_58_reg_577 = state_data_V_q1.read();
    }
}

void addRoundKey4::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void addRoundKey4::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void addRoundKey4::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void addRoundKey4::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void addRoundKey4::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void addRoundKey4::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void addRoundKey4::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void addRoundKey4::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void addRoundKey4::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void addRoundKey4::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void addRoundKey4::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void addRoundKey4::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void addRoundKey4::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void addRoundKey4::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void addRoundKey4::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void addRoundKey4::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void addRoundKey4::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void addRoundKey4::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void addRoundKey4::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void addRoundKey4::thread_grp_fu_346_p2() {
    grp_fu_346_p2 = (roundKey_data_V_q0.read() ^ reg_338.read());
}

void addRoundKey4::thread_grp_fu_353_p2() {
    grp_fu_353_p2 = (roundKey_data_V_q1.read() ^ reg_342.read());
}

void addRoundKey4::thread_op2_V_read_assign_28_fu_360_p2() {
    op2_V_read_assign_28_fu_360_p2 = (roundKey_data_V_q0.read() ^ state_data_V_load_47_reg_462.read());
}

void addRoundKey4::thread_op2_V_read_assign_29_fu_366_p2() {
    op2_V_read_assign_29_fu_366_p2 = (roundKey_data_V_q1.read() ^ state_data_V_load_48_reg_467.read());
}

void addRoundKey4::thread_op2_V_read_assign_30_fu_372_p2() {
    op2_V_read_assign_30_fu_372_p2 = (roundKey_data_V_q0.read() ^ state_data_V_load_49_reg_482.read());
}

void addRoundKey4::thread_op2_V_read_assign_31_fu_378_p2() {
    op2_V_read_assign_31_fu_378_p2 = (roundKey_data_V_q1.read() ^ state_data_V_load_50_reg_487.read());
}

void addRoundKey4::thread_op2_V_read_assign_32_fu_384_p2() {
    op2_V_read_assign_32_fu_384_p2 = (roundKey_data_V_q0.read() ^ state_data_V_load_51_reg_502.read());
}

void addRoundKey4::thread_op2_V_read_assign_33_fu_390_p2() {
    op2_V_read_assign_33_fu_390_p2 = (roundKey_data_V_q1.read() ^ state_data_V_load_52_reg_507.read());
}

void addRoundKey4::thread_op2_V_read_assign_34_fu_396_p2() {
    op2_V_read_assign_34_fu_396_p2 = (roundKey_data_V_q0.read() ^ state_data_V_load_53_reg_522.read());
}

void addRoundKey4::thread_op2_V_read_assign_35_fu_402_p2() {
    op2_V_read_assign_35_fu_402_p2 = (roundKey_data_V_q1.read() ^ state_data_V_load_54_reg_527.read());
}

void addRoundKey4::thread_op2_V_read_assign_36_fu_408_p2() {
    op2_V_read_assign_36_fu_408_p2 = (roundKey_data_V_q0.read() ^ state_data_V_load_55_reg_542.read());
}

void addRoundKey4::thread_op2_V_read_assign_37_fu_414_p2() {
    op2_V_read_assign_37_fu_414_p2 = (roundKey_data_V_q1.read() ^ state_data_V_load_56_reg_547.read());
}

void addRoundKey4::thread_op2_V_read_assign_38_fu_420_p2() {
    op2_V_read_assign_38_fu_420_p2 = (roundKey_data_V_q0.read() ^ state_data_V_load_57_reg_572.read());
}

void addRoundKey4::thread_op2_V_read_assign_39_fu_426_p2() {
    op2_V_read_assign_39_fu_426_p2 = (roundKey_data_V_q1.read() ^ state_data_V_load_58_reg_577.read());
}

void addRoundKey4::thread_roundKey_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        roundKey_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_E);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        roundKey_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_C);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        roundKey_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_A);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        roundKey_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        roundKey_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        roundKey_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        roundKey_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        roundKey_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        roundKey_data_V_address0 = "XXXX";
    }
}

void addRoundKey4::thread_roundKey_data_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        roundKey_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_F);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        roundKey_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_D);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        roundKey_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        roundKey_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_9);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        roundKey_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        roundKey_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        roundKey_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        roundKey_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_1);
    } else {
        roundKey_data_V_address1 = "XXXX";
    }
}

void addRoundKey4::thread_roundKey_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        roundKey_data_V_ce0 = ap_const_logic_1;
    } else {
        roundKey_data_V_ce0 = ap_const_logic_0;
    }
}

void addRoundKey4::thread_roundKey_data_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        roundKey_data_V_ce1 = ap_const_logic_1;
    } else {
        roundKey_data_V_ce1 = ap_const_logic_0;
    }
}

void addRoundKey4::thread_state_data_V_addr_46_reg_437() {
    state_data_V_addr_46_reg_437 =  (sc_lv<4>) (ap_const_lv64_1);
}

void addRoundKey4::thread_state_data_V_addr_47_reg_442() {
    state_data_V_addr_47_reg_442 =  (sc_lv<4>) (ap_const_lv64_2);
}

void addRoundKey4::thread_state_data_V_addr_48_reg_447() {
    state_data_V_addr_48_reg_447 =  (sc_lv<4>) (ap_const_lv64_3);
}

void addRoundKey4::thread_state_data_V_addr_49_reg_452() {
    state_data_V_addr_49_reg_452 =  (sc_lv<4>) (ap_const_lv64_4);
}

void addRoundKey4::thread_state_data_V_addr_50_reg_457() {
    state_data_V_addr_50_reg_457 =  (sc_lv<4>) (ap_const_lv64_5);
}

void addRoundKey4::thread_state_data_V_addr_51_reg_472() {
    state_data_V_addr_51_reg_472 =  (sc_lv<4>) (ap_const_lv64_6);
}

void addRoundKey4::thread_state_data_V_addr_52_reg_477() {
    state_data_V_addr_52_reg_477 =  (sc_lv<4>) (ap_const_lv64_7);
}

void addRoundKey4::thread_state_data_V_addr_53_reg_492() {
    state_data_V_addr_53_reg_492 =  (sc_lv<4>) (ap_const_lv64_8);
}

void addRoundKey4::thread_state_data_V_addr_54_reg_497() {
    state_data_V_addr_54_reg_497 =  (sc_lv<4>) (ap_const_lv64_9);
}

void addRoundKey4::thread_state_data_V_addr_55_reg_512() {
    state_data_V_addr_55_reg_512 =  (sc_lv<4>) (ap_const_lv64_A);
}

void addRoundKey4::thread_state_data_V_addr_56_reg_517() {
    state_data_V_addr_56_reg_517 =  (sc_lv<4>) (ap_const_lv64_B);
}

void addRoundKey4::thread_state_data_V_addr_57_reg_532() {
    state_data_V_addr_57_reg_532 =  (sc_lv<4>) (ap_const_lv64_C);
}

void addRoundKey4::thread_state_data_V_addr_58_reg_537() {
    state_data_V_addr_58_reg_537 =  (sc_lv<4>) (ap_const_lv64_D);
}

void addRoundKey4::thread_state_data_V_addr_59_reg_552() {
    state_data_V_addr_59_reg_552 =  (sc_lv<4>) (ap_const_lv64_E);
}

void addRoundKey4::thread_state_data_V_addr_60_reg_557() {
    state_data_V_addr_60_reg_557 =  (sc_lv<4>) (ap_const_lv64_F);
}

void addRoundKey4::thread_state_data_V_addr_reg_432() {
    state_data_V_addr_reg_432 =  (sc_lv<4>) (ap_const_lv64_0);
}

void addRoundKey4::thread_state_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        state_data_V_address0 = state_data_V_addr_59_reg_552.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        state_data_V_address0 = state_data_V_addr_57_reg_532.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_data_V_address0 = state_data_V_addr_55_reg_512.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        state_data_V_address0 = state_data_V_addr_53_reg_492.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        state_data_V_address0 = state_data_V_addr_51_reg_472.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        state_data_V_address0 = state_data_V_addr_49_reg_452.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        state_data_V_address0 = state_data_V_addr_47_reg_442.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        state_data_V_address0 = state_data_V_addr_reg_432.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_E);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_C);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_A);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        state_data_V_address0 = "XXXX";
    }
}

void addRoundKey4::thread_state_data_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        state_data_V_address1 = state_data_V_addr_60_reg_557.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        state_data_V_address1 = state_data_V_addr_58_reg_537.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_data_V_address1 = state_data_V_addr_56_reg_517.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        state_data_V_address1 = state_data_V_addr_54_reg_497.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        state_data_V_address1 = state_data_V_addr_52_reg_477.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        state_data_V_address1 = state_data_V_addr_50_reg_457.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        state_data_V_address1 = state_data_V_addr_48_reg_447.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        state_data_V_address1 = state_data_V_addr_46_reg_437.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_F);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_D);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_9);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_1);
    } else {
        state_data_V_address1 = "XXXX";
    }
}

void addRoundKey4::thread_state_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        state_data_V_ce0 = ap_const_logic_1;
    } else {
        state_data_V_ce0 = ap_const_logic_0;
    }
}

void addRoundKey4::thread_state_data_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        state_data_V_ce1 = ap_const_logic_1;
    } else {
        state_data_V_ce1 = ap_const_logic_0;
    }
}

void addRoundKey4::thread_state_data_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        state_data_V_d0 = op2_V_read_assign_38_fu_420_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_data_V_d0 = op2_V_read_assign_36_fu_408_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        state_data_V_d0 = op2_V_read_assign_34_fu_396_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        state_data_V_d0 = op2_V_read_assign_32_fu_384_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        state_data_V_d0 = op2_V_read_assign_30_fu_372_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        state_data_V_d0 = op2_V_read_assign_28_fu_360_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        state_data_V_d0 = grp_fu_346_p2.read();
    } else {
        state_data_V_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void addRoundKey4::thread_state_data_V_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        state_data_V_d1 = op2_V_read_assign_39_fu_426_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_data_V_d1 = op2_V_read_assign_37_fu_414_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        state_data_V_d1 = op2_V_read_assign_35_fu_402_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        state_data_V_d1 = op2_V_read_assign_33_fu_390_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        state_data_V_d1 = op2_V_read_assign_31_fu_378_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        state_data_V_d1 = op2_V_read_assign_29_fu_366_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        state_data_V_d1 = grp_fu_353_p2.read();
    } else {
        state_data_V_d1 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void addRoundKey4::thread_state_data_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        state_data_V_we0 = ap_const_logic_1;
    } else {
        state_data_V_we0 = ap_const_logic_0;
    }
}

void addRoundKey4::thread_state_data_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        state_data_V_we1 = ap_const_logic_1;
    } else {
        state_data_V_we1 = ap_const_logic_0;
    }
}

void addRoundKey4::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
            break;
    }
}

}

