// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _keyExpansion5_HH_
#define _keyExpansion5_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "AESEncrypt_TopFundEe.h"
#include "keyExpansion5_sbobkb.h"
#include "keyExpansion5_rcocud.h"

namespace ap_rtl {

struct keyExpansion5 : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > masterKey_data_V_address0;
    sc_out< sc_logic > masterKey_data_V_ce0;
    sc_in< sc_lv<8> > masterKey_data_V_q0;
    sc_out< sc_lv<8> > expandedKey_V_address0;
    sc_out< sc_logic > expandedKey_V_ce0;
    sc_out< sc_logic > expandedKey_V_we0;
    sc_out< sc_lv<8> > expandedKey_V_d0;
    sc_in< sc_lv<8> > expandedKey_V_q0;


    // Module declarations
    keyExpansion5(sc_module_name name);
    SC_HAS_PROCESS(keyExpansion5);

    ~keyExpansion5();

    sc_trace_file* mVcdFile;

    keyExpansion5_sbobkb* sbox_V_U;
    keyExpansion5_rcocud* rcon_V_U;
    AESEncrypt_TopFundEe<1,1,8,8,8,8,2,8>* AESEncrypt_TopFundEe_U9;
    AESEncrypt_TopFundEe<1,1,8,8,8,8,2,8>* AESEncrypt_TopFundEe_U10;
    sc_signal< sc_lv<14> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<8> > sbox_V_address0;
    sc_signal< sc_logic > sbox_V_ce0;
    sc_signal< sc_lv<8> > sbox_V_q0;
    sc_signal< sc_lv<4> > rcon_V_address0;
    sc_signal< sc_logic > rcon_V_ce0;
    sc_signal< sc_lv<8> > rcon_V_q0;
    sc_signal< sc_lv<3> > col_1_fu_572_p2;
    sc_signal< sc_lv<3> > col_1_reg_840;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<8> > tmp_cast1_fu_578_p1;
    sc_signal< sc_lv<8> > tmp_cast1_reg_845;
    sc_signal< sc_lv<1> > exitcond2_fu_566_p2;
    sc_signal< sc_lv<6> > tmp_cast_fu_582_p1;
    sc_signal< sc_lv<6> > tmp_cast_reg_850;
    sc_signal< sc_lv<3> > row_fu_592_p2;
    sc_signal< sc_lv<3> > row_reg_858;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > exitcond4_fu_586_p2;
    sc_signal< sc_lv<8> > next_mul_fu_620_p2;
    sc_signal< sc_lv<8> > next_mul_reg_868;
    sc_signal< sc_lv<8> > tmp_6_fu_626_p2;
    sc_signal< sc_lv<8> > tmp_6_reg_873;
    sc_signal< sc_lv<8> > tmp_4_cast_fu_647_p1;
    sc_signal< sc_lv<8> > tmp_4_cast_reg_881;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > exitcond3_fu_635_p2;
    sc_signal< sc_lv<3> > row_1_fu_657_p2;
    sc_signal< sc_lv<3> > row_1_reg_889;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<8> > next_mul1_fu_663_p2;
    sc_signal< sc_lv<8> > next_mul1_reg_894;
    sc_signal< sc_lv<1> > exitcond5_fu_651_p2;
    sc_signal< sc_lv<2> > tmp_32_fu_679_p1;
    sc_signal< sc_lv<2> > tmp_32_reg_904;
    sc_signal< sc_lv<1> > tmp_7_fu_687_p2;
    sc_signal< sc_lv<1> > tmp_7_reg_908;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<3> > i_fu_699_p2;
    sc_signal< sc_lv<3> > i_reg_923;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<2> > tmp_33_fu_705_p1;
    sc_signal< sc_lv<2> > tmp_33_reg_928;
    sc_signal< sc_lv<1> > exitcond_i_fu_693_p2;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<8> > tmp_9_cast_fu_756_p1;
    sc_signal< sc_lv<8> > tmp_9_cast_reg_950;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<8> > tmp_6_cast_fu_766_p1;
    sc_signal< sc_lv<8> > tmp_6_cast_reg_955;
    sc_signal< sc_lv<3> > row_2_fu_776_p2;
    sc_signal< sc_lv<3> > row_2_reg_963;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<8> > next_mul2_fu_782_p2;
    sc_signal< sc_lv<8> > next_mul2_reg_968;
    sc_signal< sc_lv<1> > exitcond_fu_770_p2;
    sc_signal< sc_lv<8> > tmp_11_fu_798_p2;
    sc_signal< sc_lv<8> > tmp_11_reg_978;
    sc_signal< sc_lv<8> > rhs_V_fu_807_p6;
    sc_signal< sc_lv<8> > rhs_V_reg_983;
    sc_signal< sc_lv<6> > col_fu_821_p2;
    sc_signal< sc_lv<3> > col_assign_reg_135;
    sc_signal< sc_lv<3> > row_assign_reg_146;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<8> > phi_mul_reg_157;
    sc_signal< sc_lv<8> > temp_3_V_5_reg_493;
    sc_signal< sc_lv<8> > temp_3_V_reg_168;
    sc_signal< sc_lv<8> > temp_2_V_3_5_reg_506;
    sc_signal< sc_lv<8> > temp_2_V_3_reg_180;
    sc_signal< sc_lv<8> > temp_1_V_5_reg_519;
    sc_signal< sc_lv<8> > temp_1_V_reg_192;
    sc_signal< sc_lv<8> > temp_0_V_1_reg_532;
    sc_signal< sc_lv<8> > temp_0_V_reg_204;
    sc_signal< sc_lv<6> > col1_reg_216;
    sc_signal< sc_lv<8> > temp_2_V_reg_228;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<8> > temp_1_V_1_reg_239;
    sc_signal< sc_lv<8> > temp_0_V_4_reg_250;
    sc_signal< sc_lv<8> > temp_3_V_6_reg_261;
    sc_signal< sc_lv<3> > row2_reg_272;
    sc_signal< sc_lv<8> > phi_mul1_reg_283;
    sc_signal< sc_lv<8> > temp_2_V_be_reg_294;
    sc_signal< sc_lv<8> > temp_1_V_1_be_reg_312;
    sc_signal< sc_lv<8> > temp_0_V_5_be_reg_330;
    sc_signal< sc_lv<8> > temp_3_V_8_be_reg_348;
    sc_signal< sc_lv<8> > temp_3_V_3_reg_366;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<8> > temp_2_V_3_3_reg_377;
    sc_signal< sc_lv<8> > temp_1_V_3_reg_388;
    sc_signal< sc_lv<8> > temp_0_V_3_reg_399;
    sc_signal< sc_lv<3> > i_i_reg_410;
    sc_signal< sc_lv<8> > temp_3_V_3_be_reg_421;
    sc_signal< sc_lv<8> > temp_2_V_3_3_be_reg_439;
    sc_signal< sc_lv<8> > temp_1_V_3_be_reg_457;
    sc_signal< sc_lv<8> > temp_0_V_3_be_reg_475;
    sc_signal< sc_lv<8> > temp_0_V_2_fu_749_p2;
    sc_signal< sc_lv<3> > row3_reg_544;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<8> > phi_mul2_reg_555;
    sc_signal< sc_lv<64> > tmp_35_cast_fu_615_p1;
    sc_signal< sc_lv<64> > tmp_37_cast_fu_631_p1;
    sc_signal< sc_lv<64> > tmp_39_cast_fu_674_p1;
    sc_signal< sc_lv<64> > tmp_4_i_fu_723_p1;
    sc_signal< sc_lv<64> > tmp_3_fu_744_p1;
    sc_signal< sc_lv<64> > tmp_41_cast_fu_793_p1;
    sc_signal< sc_lv<64> > tmp_42_cast_fu_827_p1;
    sc_signal< sc_lv<8> > r_V_fu_831_p2;
    sc_signal< sc_lv<5> > tmp_4_fu_598_p3;
    sc_signal< sc_lv<6> > tmp_34_cast_fu_606_p1;
    sc_signal< sc_lv<6> > tmp_5_fu_610_p2;
    sc_signal< sc_lv<6> > tmp_s_fu_641_p2;
    sc_signal< sc_lv<8> > tmp_8_fu_669_p2;
    sc_signal< sc_lv<2> > tmp_fu_683_p1;
    sc_signal< sc_lv<2> > tmp_9_fu_709_p5;
    sc_signal< sc_lv<8> > tmp_9_fu_709_p6;
    sc_signal< sc_lv<4> > p_lshr_f_cast_fu_728_p4;
    sc_signal< sc_lv<4> > addconv_fu_738_p2;
    sc_signal< sc_lv<6> > tmp_2_fu_760_p2;
    sc_signal< sc_lv<8> > tmp_10_fu_788_p2;
    sc_signal< sc_lv<2> > rhs_V_fu_807_p5;
    sc_signal< sc_lv<14> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<14> ap_ST_fsm_state1;
    static const sc_lv<14> ap_ST_fsm_state2;
    static const sc_lv<14> ap_ST_fsm_state3;
    static const sc_lv<14> ap_ST_fsm_state4;
    static const sc_lv<14> ap_ST_fsm_state5;
    static const sc_lv<14> ap_ST_fsm_state6;
    static const sc_lv<14> ap_ST_fsm_state7;
    static const sc_lv<14> ap_ST_fsm_state8;
    static const sc_lv<14> ap_ST_fsm_state9;
    static const sc_lv<14> ap_ST_fsm_state10;
    static const sc_lv<14> ap_ST_fsm_state11;
    static const sc_lv<14> ap_ST_fsm_state12;
    static const sc_lv<14> ap_ST_fsm_state13;
    static const sc_lv<14> ap_ST_fsm_state14;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<6> ap_const_lv6_4;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<8> ap_const_lv8_2C;
    static const sc_lv<6> ap_const_lv6_2C;
    static const sc_lv<6> ap_const_lv6_3F;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<6> ap_const_lv6_3C;
    static const sc_lv<6> ap_const_lv6_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_addconv_fu_738_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_col_1_fu_572_p2();
    void thread_col_fu_821_p2();
    void thread_exitcond2_fu_566_p2();
    void thread_exitcond3_fu_635_p2();
    void thread_exitcond4_fu_586_p2();
    void thread_exitcond5_fu_651_p2();
    void thread_exitcond_fu_770_p2();
    void thread_exitcond_i_fu_693_p2();
    void thread_expandedKey_V_address0();
    void thread_expandedKey_V_ce0();
    void thread_expandedKey_V_d0();
    void thread_expandedKey_V_we0();
    void thread_i_fu_699_p2();
    void thread_masterKey_data_V_address0();
    void thread_masterKey_data_V_ce0();
    void thread_next_mul1_fu_663_p2();
    void thread_next_mul2_fu_782_p2();
    void thread_next_mul_fu_620_p2();
    void thread_p_lshr_f_cast_fu_728_p4();
    void thread_r_V_fu_831_p2();
    void thread_rcon_V_address0();
    void thread_rcon_V_ce0();
    void thread_rhs_V_fu_807_p5();
    void thread_row_1_fu_657_p2();
    void thread_row_2_fu_776_p2();
    void thread_row_fu_592_p2();
    void thread_sbox_V_address0();
    void thread_sbox_V_ce0();
    void thread_temp_0_V_2_fu_749_p2();
    void thread_tmp_10_fu_788_p2();
    void thread_tmp_11_fu_798_p2();
    void thread_tmp_2_fu_760_p2();
    void thread_tmp_32_fu_679_p1();
    void thread_tmp_33_fu_705_p1();
    void thread_tmp_34_cast_fu_606_p1();
    void thread_tmp_35_cast_fu_615_p1();
    void thread_tmp_37_cast_fu_631_p1();
    void thread_tmp_39_cast_fu_674_p1();
    void thread_tmp_3_fu_744_p1();
    void thread_tmp_41_cast_fu_793_p1();
    void thread_tmp_42_cast_fu_827_p1();
    void thread_tmp_4_cast_fu_647_p1();
    void thread_tmp_4_fu_598_p3();
    void thread_tmp_4_i_fu_723_p1();
    void thread_tmp_5_fu_610_p2();
    void thread_tmp_6_cast_fu_766_p1();
    void thread_tmp_6_fu_626_p2();
    void thread_tmp_7_fu_687_p2();
    void thread_tmp_8_fu_669_p2();
    void thread_tmp_9_cast_fu_756_p1();
    void thread_tmp_9_fu_709_p5();
    void thread_tmp_cast1_fu_578_p1();
    void thread_tmp_cast_fu_582_p1();
    void thread_tmp_fu_683_p1();
    void thread_tmp_s_fu_641_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
