// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "shiftRowRight.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic shiftRowRight::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic shiftRowRight::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> shiftRowRight::ap_ST_fsm_state1 = "1";
const sc_lv<4> shiftRowRight::ap_ST_fsm_state2 = "10";
const sc_lv<4> shiftRowRight::ap_ST_fsm_state3 = "100";
const sc_lv<4> shiftRowRight::ap_ST_fsm_state4 = "1000";
const sc_lv<32> shiftRowRight::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> shiftRowRight::ap_const_lv32_1 = "1";
const sc_lv<1> shiftRowRight::ap_const_lv1_0 = "0";
const sc_lv<32> shiftRowRight::ap_const_lv32_3 = "11";
const sc_lv<3> shiftRowRight::ap_const_lv3_0 = "000";
const sc_lv<32> shiftRowRight::ap_const_lv32_2 = "10";
const sc_lv<1> shiftRowRight::ap_const_lv1_1 = "1";
const sc_lv<2> shiftRowRight::ap_const_lv2_0 = "00";
const sc_lv<2> shiftRowRight::ap_const_lv2_1 = "1";
const sc_lv<2> shiftRowRight::ap_const_lv2_2 = "10";
const sc_lv<2> shiftRowRight::ap_const_lv2_3 = "11";
const sc_lv<3> shiftRowRight::ap_const_lv3_4 = "100";
const sc_lv<3> shiftRowRight::ap_const_lv3_1 = "1";
const sc_lv<62> shiftRowRight::ap_const_lv62_3 = "11";
const bool shiftRowRight::ap_const_boolean_1 = true;

shiftRowRight::shiftRowRight(sc_module_name name) : sc_module(name), mVcdFile(0) {
    AESEncrypt_TopFundEe_U24 = new AESEncrypt_TopFundEe<1,1,8,8,8,8,2,8>("AESEncrypt_TopFundEe_U24");
    AESEncrypt_TopFundEe_U24->din0(tempRow_3_V_fu_30);
    AESEncrypt_TopFundEe_U24->din1(tempRow_3_V_1_fu_34);
    AESEncrypt_TopFundEe_U24->din2(tempRow_3_V_2_fu_38);
    AESEncrypt_TopFundEe_U24->din3(tempRow_3_V_3_fu_42);
    AESEncrypt_TopFundEe_U24->din4(tmp_3_fu_182_p5);
    AESEncrypt_TopFundEe_U24->dout(tmp_3_fu_182_p6);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_AESMatrix_data_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_1_fu_110_p3 );
    sensitive << ( tmp_2_cast_fu_173_p1 );

    SC_METHOD(thread_AESMatrix_data_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_AESMatrix_data_V_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_3_fu_182_p6 );

    SC_METHOD(thread_AESMatrix_data_V_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_139_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_139_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_139_p2 );

    SC_METHOD(thread_col_1_fu_145_p2);
    sensitive << ( col1_reg_77 );

    SC_METHOD(thread_col_2_fu_94_p2);
    sensitive << ( col_reg_66 );

    SC_METHOD(thread_exitcond8_fu_88_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( col_reg_66 );

    SC_METHOD(thread_exitcond_fu_139_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( col1_reg_77 );

    SC_METHOD(thread_tmp_1_fu_110_p3);
    sensitive << ( tmp_cast_fu_104_p2 );

    SC_METHOD(thread_tmp_2_cast1_fu_169_p1);
    sensitive << ( tmp_2_fu_163_p2 );

    SC_METHOD(thread_tmp_2_cast_fu_173_p1);
    sensitive << ( tmp_2_cast1_fu_169_p1 );

    SC_METHOD(thread_tmp_2_fu_163_p2);
    sensitive << ( col1_reg_77 );

    SC_METHOD(thread_tmp_3_fu_182_p5);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( col1_reg_77 );

    SC_METHOD(thread_tmp_cast_fu_104_p2);
    sensitive << ( tmp_fu_100_p1 );

    SC_METHOD(thread_tmp_fu_100_p1);
    sensitive << ( col_reg_66 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond8_fu_88_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_139_p2 );

    ap_CS_fsm = "0001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "shiftRowRight_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, AESMatrix_data_V_address0, "(port)AESMatrix_data_V_address0");
    sc_trace(mVcdFile, AESMatrix_data_V_ce0, "(port)AESMatrix_data_V_ce0");
    sc_trace(mVcdFile, AESMatrix_data_V_we0, "(port)AESMatrix_data_V_we0");
    sc_trace(mVcdFile, AESMatrix_data_V_d0, "(port)AESMatrix_data_V_d0");
    sc_trace(mVcdFile, AESMatrix_data_V_q0, "(port)AESMatrix_data_V_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, col_2_fu_94_p2, "col_2_fu_94_p2");
    sc_trace(mVcdFile, col_2_reg_224, "col_2_reg_224");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_100_p1, "tmp_fu_100_p1");
    sc_trace(mVcdFile, tmp_reg_229, "tmp_reg_229");
    sc_trace(mVcdFile, exitcond8_fu_88_p2, "exitcond8_fu_88_p2");
    sc_trace(mVcdFile, col_1_fu_145_p2, "col_1_fu_145_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, col_reg_66, "col_reg_66");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, col1_reg_77, "col1_reg_77");
    sc_trace(mVcdFile, exitcond_fu_139_p2, "exitcond_fu_139_p2");
    sc_trace(mVcdFile, tmp_1_fu_110_p3, "tmp_1_fu_110_p3");
    sc_trace(mVcdFile, tmp_2_cast_fu_173_p1, "tmp_2_cast_fu_173_p1");
    sc_trace(mVcdFile, tempRow_3_V_fu_30, "tempRow_3_V_fu_30");
    sc_trace(mVcdFile, tempRow_3_V_1_fu_34, "tempRow_3_V_1_fu_34");
    sc_trace(mVcdFile, tempRow_3_V_2_fu_38, "tempRow_3_V_2_fu_38");
    sc_trace(mVcdFile, tempRow_3_V_3_fu_42, "tempRow_3_V_3_fu_42");
    sc_trace(mVcdFile, tmp_3_fu_182_p6, "tmp_3_fu_182_p6");
    sc_trace(mVcdFile, tmp_cast_fu_104_p2, "tmp_cast_fu_104_p2");
    sc_trace(mVcdFile, tmp_2_fu_163_p2, "tmp_2_fu_163_p2");
    sc_trace(mVcdFile, tmp_2_cast1_fu_169_p1, "tmp_2_cast1_fu_169_p1");
    sc_trace(mVcdFile, tmp_3_fu_182_p5, "tmp_3_fu_182_p5");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

shiftRowRight::~shiftRowRight() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete AESEncrypt_TopFundEe_U24;
}

void shiftRowRight::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(exitcond8_fu_88_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        col1_reg_77 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(exitcond_fu_139_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        col1_reg_77 = col_1_fu_145_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        col_reg_66 = col_2_reg_224.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        col_reg_66 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        col_2_reg_224 = col_2_fu_94_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,2,2>(tmp_reg_229.read(), ap_const_lv2_1))) {
        tempRow_3_V_1_fu_34 = AESMatrix_data_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,2,2>(tmp_reg_229.read(), ap_const_lv2_2))) {
        tempRow_3_V_2_fu_38 = AESMatrix_data_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,2,2>(tmp_reg_229.read(), ap_const_lv2_3))) {
        tempRow_3_V_3_fu_42 = AESMatrix_data_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,2,2>(tmp_reg_229.read(), ap_const_lv2_0))) {
        tempRow_3_V_fu_30 = AESMatrix_data_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(exitcond8_fu_88_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        tmp_reg_229 = tmp_fu_100_p1.read();
    }
}

void shiftRowRight::thread_AESMatrix_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        AESMatrix_data_V_address0 =  (sc_lv<4>) (tmp_2_cast_fu_173_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        AESMatrix_data_V_address0 =  (sc_lv<4>) (tmp_1_fu_110_p3.read());
    } else {
        AESMatrix_data_V_address0 = "XXXX";
    }
}

void shiftRowRight::thread_AESMatrix_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        AESMatrix_data_V_ce0 = ap_const_logic_1;
    } else {
        AESMatrix_data_V_ce0 = ap_const_logic_0;
    }
}

void shiftRowRight::thread_AESMatrix_data_V_d0() {
    AESMatrix_data_V_d0 = tmp_3_fu_182_p6.read();
}

void shiftRowRight::thread_AESMatrix_data_V_we0() {
    if ((esl_seteq<1,1,1>(exitcond_fu_139_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        AESMatrix_data_V_we0 = ap_const_logic_1;
    } else {
        AESMatrix_data_V_we0 = ap_const_logic_0;
    }
}

void shiftRowRight::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void shiftRowRight::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void shiftRowRight::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void shiftRowRight::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void shiftRowRight::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(exitcond_fu_139_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void shiftRowRight::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void shiftRowRight::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond_fu_139_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void shiftRowRight::thread_col_1_fu_145_p2() {
    col_1_fu_145_p2 = (!col1_reg_77.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(col1_reg_77.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void shiftRowRight::thread_col_2_fu_94_p2() {
    col_2_fu_94_p2 = (!col_reg_66.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(col_reg_66.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void shiftRowRight::thread_exitcond8_fu_88_p2() {
    exitcond8_fu_88_p2 = (!col_reg_66.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(col_reg_66.read() == ap_const_lv3_4);
}

void shiftRowRight::thread_exitcond_fu_139_p2() {
    exitcond_fu_139_p2 = (!col1_reg_77.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(col1_reg_77.read() == ap_const_lv3_4);
}

void shiftRowRight::thread_tmp_1_fu_110_p3() {
    tmp_1_fu_110_p3 = esl_concat<62,2>(ap_const_lv62_3, tmp_cast_fu_104_p2.read());
}

void shiftRowRight::thread_tmp_2_cast1_fu_169_p1() {
    tmp_2_cast1_fu_169_p1 = esl_sext<4,3>(tmp_2_fu_163_p2.read());
}

void shiftRowRight::thread_tmp_2_cast_fu_173_p1() {
    tmp_2_cast_fu_173_p1 = esl_zext<64,4>(tmp_2_cast1_fu_169_p1.read());
}

void shiftRowRight::thread_tmp_2_fu_163_p2() {
    tmp_2_fu_163_p2 = (col1_reg_77.read() ^ ap_const_lv3_4);
}

void shiftRowRight::thread_tmp_3_fu_182_p5() {
    tmp_3_fu_182_p5 = col1_reg_77.read().range(2-1, 0);
}

void shiftRowRight::thread_tmp_cast_fu_104_p2() {
    tmp_cast_fu_104_p2 = (!ap_const_lv2_3.is_01() || !tmp_fu_100_p1.read().is_01())? sc_lv<2>(): (sc_bigint<2>(ap_const_lv2_3) + sc_biguint<2>(tmp_fu_100_p1.read()));
}

void shiftRowRight::thread_tmp_fu_100_p1() {
    tmp_fu_100_p1 = col_reg_66.read().range(2-1, 0);
}

void shiftRowRight::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond8_fu_88_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(exitcond_fu_139_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

