// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _substituteBytes_HH_
#define _substituteBytes_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "substituteBytes_seOg.h"

namespace ap_rtl {

struct substituteBytes : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > state_data_V_address0;
    sc_out< sc_logic > state_data_V_ce0;
    sc_out< sc_logic > state_data_V_we0;
    sc_out< sc_lv<8> > state_data_V_d0;
    sc_in< sc_lv<8> > state_data_V_q0;
    sc_out< sc_lv<4> > state_data_V_address1;
    sc_out< sc_logic > state_data_V_ce1;
    sc_out< sc_logic > state_data_V_we1;
    sc_out< sc_lv<8> > state_data_V_d1;
    sc_in< sc_lv<8> > state_data_V_q1;


    // Module declarations
    substituteBytes(sc_module_name name);
    SC_HAS_PROCESS(substituteBytes);

    ~substituteBytes();

    sc_trace_file* mVcdFile;

    substituteBytes_seOg* sbox_V_U;
    sc_signal< sc_lv<16> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<8> > sbox_V_address0;
    sc_signal< sc_logic > sbox_V_ce0;
    sc_signal< sc_lv<8> > sbox_V_q0;
    sc_signal< sc_lv<8> > sbox_V_address1;
    sc_signal< sc_logic > sbox_V_ce1;
    sc_signal< sc_lv<8> > sbox_V_q1;
    sc_signal< sc_lv<8> > reg_324;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<8> > reg_328;
    sc_signal< sc_lv<8> > reg_332;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<8> > reg_336;
    sc_signal< sc_lv<4> > state_data_V_addr_reg_412;
    sc_signal< sc_lv<4> > state_data_V_addr_1_reg_417;
    sc_signal< sc_lv<4> > state_data_V_addr_2_reg_422;
    sc_signal< sc_lv<4> > state_data_V_addr_3_reg_427;
    sc_signal< sc_lv<4> > state_data_V_addr_4_reg_432;
    sc_signal< sc_lv<4> > state_data_V_addr_5_reg_437;
    sc_signal< sc_lv<4> > state_data_V_addr_6_reg_442;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<4> > state_data_V_addr_7_reg_447;
    sc_signal< sc_lv<8> > state_data_V_load_4_reg_452;
    sc_signal< sc_lv<8> > state_data_V_load_5_reg_457;
    sc_signal< sc_lv<4> > state_data_V_addr_8_reg_462;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<4> > state_data_V_addr_9_reg_467;
    sc_signal< sc_lv<8> > state_data_V_load_6_reg_472;
    sc_signal< sc_lv<8> > state_data_V_load_7_reg_477;
    sc_signal< sc_lv<4> > state_data_V_addr_10_reg_482;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<4> > state_data_V_addr_11_reg_487;
    sc_signal< sc_lv<8> > state_data_V_load_8_reg_492;
    sc_signal< sc_lv<8> > state_data_V_load_9_reg_497;
    sc_signal< sc_lv<4> > state_data_V_addr_12_reg_502;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<4> > state_data_V_addr_13_reg_507;
    sc_signal< sc_lv<8> > state_data_V_load_10_reg_512;
    sc_signal< sc_lv<8> > state_data_V_load_11_reg_517;
    sc_signal< sc_lv<4> > state_data_V_addr_14_reg_522;
    sc_signal< sc_lv<4> > state_data_V_addr_15_reg_527;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<64> > tmp_2_fu_340_p1;
    sc_signal< sc_lv<64> > tmp_2_0_1_fu_345_p1;
    sc_signal< sc_lv<64> > tmp_2_0_2_fu_350_p1;
    sc_signal< sc_lv<64> > tmp_2_0_3_fu_355_p1;
    sc_signal< sc_lv<64> > tmp_2_1_fu_360_p1;
    sc_signal< sc_lv<64> > tmp_2_1_1_fu_364_p1;
    sc_signal< sc_lv<64> > tmp_2_1_2_fu_368_p1;
    sc_signal< sc_lv<64> > tmp_2_1_3_fu_372_p1;
    sc_signal< sc_lv<64> > tmp_2_2_fu_376_p1;
    sc_signal< sc_lv<64> > tmp_2_2_1_fu_380_p1;
    sc_signal< sc_lv<64> > tmp_2_2_2_fu_384_p1;
    sc_signal< sc_lv<64> > tmp_2_2_3_fu_388_p1;
    sc_signal< sc_lv<64> > tmp_2_3_fu_392_p1;
    sc_signal< sc_lv<64> > tmp_2_3_1_fu_397_p1;
    sc_signal< sc_lv<64> > tmp_2_3_2_fu_402_p1;
    sc_signal< sc_lv<64> > tmp_2_3_3_fu_407_p1;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<16> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<16> ap_ST_fsm_state1;
    static const sc_lv<16> ap_ST_fsm_state2;
    static const sc_lv<16> ap_ST_fsm_state3;
    static const sc_lv<16> ap_ST_fsm_state4;
    static const sc_lv<16> ap_ST_fsm_state5;
    static const sc_lv<16> ap_ST_fsm_state6;
    static const sc_lv<16> ap_ST_fsm_state7;
    static const sc_lv<16> ap_ST_fsm_state8;
    static const sc_lv<16> ap_ST_fsm_state9;
    static const sc_lv<16> ap_ST_fsm_state10;
    static const sc_lv<16> ap_ST_fsm_state11;
    static const sc_lv<16> ap_ST_fsm_state12;
    static const sc_lv<16> ap_ST_fsm_state13;
    static const sc_lv<16> ap_ST_fsm_state14;
    static const sc_lv<16> ap_ST_fsm_state15;
    static const sc_lv<16> ap_ST_fsm_state16;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_2;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_4;
    static const sc_lv<64> ap_const_lv64_5;
    static const sc_lv<64> ap_const_lv64_6;
    static const sc_lv<64> ap_const_lv64_7;
    static const sc_lv<64> ap_const_lv64_8;
    static const sc_lv<64> ap_const_lv64_9;
    static const sc_lv<64> ap_const_lv64_A;
    static const sc_lv<64> ap_const_lv64_B;
    static const sc_lv<64> ap_const_lv64_C;
    static const sc_lv<64> ap_const_lv64_D;
    static const sc_lv<64> ap_const_lv64_E;
    static const sc_lv<64> ap_const_lv64_F;
    static const sc_lv<32> ap_const_lv32_F;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_sbox_V_address0();
    void thread_sbox_V_address1();
    void thread_sbox_V_ce0();
    void thread_sbox_V_ce1();
    void thread_state_data_V_addr_10_reg_482();
    void thread_state_data_V_addr_11_reg_487();
    void thread_state_data_V_addr_12_reg_502();
    void thread_state_data_V_addr_13_reg_507();
    void thread_state_data_V_addr_14_reg_522();
    void thread_state_data_V_addr_15_reg_527();
    void thread_state_data_V_addr_1_reg_417();
    void thread_state_data_V_addr_2_reg_422();
    void thread_state_data_V_addr_3_reg_427();
    void thread_state_data_V_addr_4_reg_432();
    void thread_state_data_V_addr_5_reg_437();
    void thread_state_data_V_addr_6_reg_442();
    void thread_state_data_V_addr_7_reg_447();
    void thread_state_data_V_addr_8_reg_462();
    void thread_state_data_V_addr_9_reg_467();
    void thread_state_data_V_addr_reg_412();
    void thread_state_data_V_address0();
    void thread_state_data_V_address1();
    void thread_state_data_V_ce0();
    void thread_state_data_V_ce1();
    void thread_state_data_V_d0();
    void thread_state_data_V_d1();
    void thread_state_data_V_we0();
    void thread_state_data_V_we1();
    void thread_tmp_2_0_1_fu_345_p1();
    void thread_tmp_2_0_2_fu_350_p1();
    void thread_tmp_2_0_3_fu_355_p1();
    void thread_tmp_2_1_1_fu_364_p1();
    void thread_tmp_2_1_2_fu_368_p1();
    void thread_tmp_2_1_3_fu_372_p1();
    void thread_tmp_2_1_fu_360_p1();
    void thread_tmp_2_2_1_fu_380_p1();
    void thread_tmp_2_2_2_fu_384_p1();
    void thread_tmp_2_2_3_fu_388_p1();
    void thread_tmp_2_2_fu_376_p1();
    void thread_tmp_2_3_1_fu_397_p1();
    void thread_tmp_2_3_2_fu_402_p1();
    void thread_tmp_2_3_3_fu_407_p1();
    void thread_tmp_2_3_fu_392_p1();
    void thread_tmp_2_fu_340_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
