// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "substituteBytes.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic substituteBytes::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic substituteBytes::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> substituteBytes::ap_ST_fsm_state1 = "1";
const sc_lv<16> substituteBytes::ap_ST_fsm_state2 = "10";
const sc_lv<16> substituteBytes::ap_ST_fsm_state3 = "100";
const sc_lv<16> substituteBytes::ap_ST_fsm_state4 = "1000";
const sc_lv<16> substituteBytes::ap_ST_fsm_state5 = "10000";
const sc_lv<16> substituteBytes::ap_ST_fsm_state6 = "100000";
const sc_lv<16> substituteBytes::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> substituteBytes::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> substituteBytes::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> substituteBytes::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> substituteBytes::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> substituteBytes::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> substituteBytes::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> substituteBytes::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> substituteBytes::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> substituteBytes::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> substituteBytes::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> substituteBytes::ap_const_lv32_1 = "1";
const sc_lv<32> substituteBytes::ap_const_lv32_7 = "111";
const sc_lv<32> substituteBytes::ap_const_lv32_2 = "10";
const sc_lv<32> substituteBytes::ap_const_lv32_8 = "1000";
const sc_lv<32> substituteBytes::ap_const_lv32_3 = "11";
const sc_lv<32> substituteBytes::ap_const_lv32_4 = "100";
const sc_lv<32> substituteBytes::ap_const_lv32_5 = "101";
const sc_lv<32> substituteBytes::ap_const_lv32_6 = "110";
const sc_lv<32> substituteBytes::ap_const_lv32_9 = "1001";
const sc_lv<32> substituteBytes::ap_const_lv32_A = "1010";
const sc_lv<32> substituteBytes::ap_const_lv32_B = "1011";
const sc_lv<32> substituteBytes::ap_const_lv32_C = "1100";
const sc_lv<32> substituteBytes::ap_const_lv32_D = "1101";
const sc_lv<32> substituteBytes::ap_const_lv32_E = "1110";
const sc_lv<64> substituteBytes::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> substituteBytes::ap_const_lv64_1 = "1";
const sc_lv<64> substituteBytes::ap_const_lv64_2 = "10";
const sc_lv<64> substituteBytes::ap_const_lv64_3 = "11";
const sc_lv<64> substituteBytes::ap_const_lv64_4 = "100";
const sc_lv<64> substituteBytes::ap_const_lv64_5 = "101";
const sc_lv<64> substituteBytes::ap_const_lv64_6 = "110";
const sc_lv<64> substituteBytes::ap_const_lv64_7 = "111";
const sc_lv<64> substituteBytes::ap_const_lv64_8 = "1000";
const sc_lv<64> substituteBytes::ap_const_lv64_9 = "1001";
const sc_lv<64> substituteBytes::ap_const_lv64_A = "1010";
const sc_lv<64> substituteBytes::ap_const_lv64_B = "1011";
const sc_lv<64> substituteBytes::ap_const_lv64_C = "1100";
const sc_lv<64> substituteBytes::ap_const_lv64_D = "1101";
const sc_lv<64> substituteBytes::ap_const_lv64_E = "1110";
const sc_lv<64> substituteBytes::ap_const_lv64_F = "1111";
const sc_lv<32> substituteBytes::ap_const_lv32_F = "1111";
const bool substituteBytes::ap_const_boolean_1 = true;

substituteBytes::substituteBytes(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sbox_V_U = new substituteBytes_seOg("sbox_V_U");
    sbox_V_U->clk(ap_clk);
    sbox_V_U->reset(ap_rst);
    sbox_V_U->address0(sbox_V_address0);
    sbox_V_U->ce0(sbox_V_ce0);
    sbox_V_U->q0(sbox_V_q0);
    sbox_V_U->address1(sbox_V_address1);
    sbox_V_U->ce1(sbox_V_ce1);
    sbox_V_U->q1(sbox_V_q1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_sbox_V_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( tmp_2_fu_340_p1 );
    sensitive << ( tmp_2_0_2_fu_350_p1 );
    sensitive << ( tmp_2_1_fu_360_p1 );
    sensitive << ( tmp_2_1_2_fu_368_p1 );
    sensitive << ( tmp_2_2_fu_376_p1 );
    sensitive << ( tmp_2_2_2_fu_384_p1 );
    sensitive << ( tmp_2_3_fu_392_p1 );
    sensitive << ( tmp_2_3_2_fu_402_p1 );

    SC_METHOD(thread_sbox_V_address1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( tmp_2_0_1_fu_345_p1 );
    sensitive << ( tmp_2_0_3_fu_355_p1 );
    sensitive << ( tmp_2_1_1_fu_364_p1 );
    sensitive << ( tmp_2_1_3_fu_372_p1 );
    sensitive << ( tmp_2_2_1_fu_380_p1 );
    sensitive << ( tmp_2_2_3_fu_388_p1 );
    sensitive << ( tmp_2_3_1_fu_397_p1 );
    sensitive << ( tmp_2_3_3_fu_407_p1 );

    SC_METHOD(thread_sbox_V_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_sbox_V_ce1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_state_data_V_addr_10_reg_482);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_state_data_V_addr_11_reg_487);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_state_data_V_addr_12_reg_502);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_state_data_V_addr_13_reg_507);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_state_data_V_addr_14_reg_522);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_state_data_V_addr_15_reg_527);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_state_data_V_addr_1_reg_417);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_state_data_V_addr_2_reg_422);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_state_data_V_addr_3_reg_427);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_state_data_V_addr_4_reg_432);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_state_data_V_addr_5_reg_437);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_state_data_V_addr_6_reg_442);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_state_data_V_addr_7_reg_447);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_state_data_V_addr_8_reg_462);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_state_data_V_addr_9_reg_467);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_state_data_V_addr_reg_412);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_state_data_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( state_data_V_addr_reg_412 );
    sensitive << ( state_data_V_addr_2_reg_422 );
    sensitive << ( state_data_V_addr_4_reg_432 );
    sensitive << ( state_data_V_addr_6_reg_442 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( state_data_V_addr_8_reg_462 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( state_data_V_addr_10_reg_482 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( state_data_V_addr_12_reg_502 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( state_data_V_addr_14_reg_522 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_address1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( state_data_V_addr_1_reg_417 );
    sensitive << ( state_data_V_addr_3_reg_427 );
    sensitive << ( state_data_V_addr_5_reg_437 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( state_data_V_addr_7_reg_447 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( state_data_V_addr_9_reg_467 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( state_data_V_addr_11_reg_487 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( state_data_V_addr_13_reg_507 );
    sensitive << ( state_data_V_addr_15_reg_527 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_d0);
    sensitive << ( sbox_V_q0 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_d1);
    sensitive << ( sbox_V_q1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_we0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_state_data_V_we1);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_tmp_2_0_1_fu_345_p1);
    sensitive << ( reg_328 );

    SC_METHOD(thread_tmp_2_0_2_fu_350_p1);
    sensitive << ( reg_332 );

    SC_METHOD(thread_tmp_2_0_3_fu_355_p1);
    sensitive << ( reg_336 );

    SC_METHOD(thread_tmp_2_1_1_fu_364_p1);
    sensitive << ( state_data_V_load_5_reg_457 );

    SC_METHOD(thread_tmp_2_1_2_fu_368_p1);
    sensitive << ( state_data_V_load_6_reg_472 );

    SC_METHOD(thread_tmp_2_1_3_fu_372_p1);
    sensitive << ( state_data_V_load_7_reg_477 );

    SC_METHOD(thread_tmp_2_1_fu_360_p1);
    sensitive << ( state_data_V_load_4_reg_452 );

    SC_METHOD(thread_tmp_2_2_1_fu_380_p1);
    sensitive << ( state_data_V_load_9_reg_497 );

    SC_METHOD(thread_tmp_2_2_2_fu_384_p1);
    sensitive << ( state_data_V_load_10_reg_512 );

    SC_METHOD(thread_tmp_2_2_3_fu_388_p1);
    sensitive << ( state_data_V_load_11_reg_517 );

    SC_METHOD(thread_tmp_2_2_fu_376_p1);
    sensitive << ( state_data_V_load_8_reg_492 );

    SC_METHOD(thread_tmp_2_3_1_fu_397_p1);
    sensitive << ( reg_328 );

    SC_METHOD(thread_tmp_2_3_2_fu_402_p1);
    sensitive << ( reg_332 );

    SC_METHOD(thread_tmp_2_3_3_fu_407_p1);
    sensitive << ( reg_336 );

    SC_METHOD(thread_tmp_2_3_fu_392_p1);
    sensitive << ( reg_324 );

    SC_METHOD(thread_tmp_2_fu_340_p1);
    sensitive << ( reg_324 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    ap_CS_fsm = "0000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "substituteBytes_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, state_data_V_address0, "(port)state_data_V_address0");
    sc_trace(mVcdFile, state_data_V_ce0, "(port)state_data_V_ce0");
    sc_trace(mVcdFile, state_data_V_we0, "(port)state_data_V_we0");
    sc_trace(mVcdFile, state_data_V_d0, "(port)state_data_V_d0");
    sc_trace(mVcdFile, state_data_V_q0, "(port)state_data_V_q0");
    sc_trace(mVcdFile, state_data_V_address1, "(port)state_data_V_address1");
    sc_trace(mVcdFile, state_data_V_ce1, "(port)state_data_V_ce1");
    sc_trace(mVcdFile, state_data_V_we1, "(port)state_data_V_we1");
    sc_trace(mVcdFile, state_data_V_d1, "(port)state_data_V_d1");
    sc_trace(mVcdFile, state_data_V_q1, "(port)state_data_V_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, sbox_V_address0, "sbox_V_address0");
    sc_trace(mVcdFile, sbox_V_ce0, "sbox_V_ce0");
    sc_trace(mVcdFile, sbox_V_q0, "sbox_V_q0");
    sc_trace(mVcdFile, sbox_V_address1, "sbox_V_address1");
    sc_trace(mVcdFile, sbox_V_ce1, "sbox_V_ce1");
    sc_trace(mVcdFile, sbox_V_q1, "sbox_V_q1");
    sc_trace(mVcdFile, reg_324, "reg_324");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, reg_328, "reg_328");
    sc_trace(mVcdFile, reg_332, "reg_332");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, reg_336, "reg_336");
    sc_trace(mVcdFile, state_data_V_addr_reg_412, "state_data_V_addr_reg_412");
    sc_trace(mVcdFile, state_data_V_addr_1_reg_417, "state_data_V_addr_1_reg_417");
    sc_trace(mVcdFile, state_data_V_addr_2_reg_422, "state_data_V_addr_2_reg_422");
    sc_trace(mVcdFile, state_data_V_addr_3_reg_427, "state_data_V_addr_3_reg_427");
    sc_trace(mVcdFile, state_data_V_addr_4_reg_432, "state_data_V_addr_4_reg_432");
    sc_trace(mVcdFile, state_data_V_addr_5_reg_437, "state_data_V_addr_5_reg_437");
    sc_trace(mVcdFile, state_data_V_addr_6_reg_442, "state_data_V_addr_6_reg_442");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, state_data_V_addr_7_reg_447, "state_data_V_addr_7_reg_447");
    sc_trace(mVcdFile, state_data_V_load_4_reg_452, "state_data_V_load_4_reg_452");
    sc_trace(mVcdFile, state_data_V_load_5_reg_457, "state_data_V_load_5_reg_457");
    sc_trace(mVcdFile, state_data_V_addr_8_reg_462, "state_data_V_addr_8_reg_462");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, state_data_V_addr_9_reg_467, "state_data_V_addr_9_reg_467");
    sc_trace(mVcdFile, state_data_V_load_6_reg_472, "state_data_V_load_6_reg_472");
    sc_trace(mVcdFile, state_data_V_load_7_reg_477, "state_data_V_load_7_reg_477");
    sc_trace(mVcdFile, state_data_V_addr_10_reg_482, "state_data_V_addr_10_reg_482");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, state_data_V_addr_11_reg_487, "state_data_V_addr_11_reg_487");
    sc_trace(mVcdFile, state_data_V_load_8_reg_492, "state_data_V_load_8_reg_492");
    sc_trace(mVcdFile, state_data_V_load_9_reg_497, "state_data_V_load_9_reg_497");
    sc_trace(mVcdFile, state_data_V_addr_12_reg_502, "state_data_V_addr_12_reg_502");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, state_data_V_addr_13_reg_507, "state_data_V_addr_13_reg_507");
    sc_trace(mVcdFile, state_data_V_load_10_reg_512, "state_data_V_load_10_reg_512");
    sc_trace(mVcdFile, state_data_V_load_11_reg_517, "state_data_V_load_11_reg_517");
    sc_trace(mVcdFile, state_data_V_addr_14_reg_522, "state_data_V_addr_14_reg_522");
    sc_trace(mVcdFile, state_data_V_addr_15_reg_527, "state_data_V_addr_15_reg_527");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, tmp_2_fu_340_p1, "tmp_2_fu_340_p1");
    sc_trace(mVcdFile, tmp_2_0_1_fu_345_p1, "tmp_2_0_1_fu_345_p1");
    sc_trace(mVcdFile, tmp_2_0_2_fu_350_p1, "tmp_2_0_2_fu_350_p1");
    sc_trace(mVcdFile, tmp_2_0_3_fu_355_p1, "tmp_2_0_3_fu_355_p1");
    sc_trace(mVcdFile, tmp_2_1_fu_360_p1, "tmp_2_1_fu_360_p1");
    sc_trace(mVcdFile, tmp_2_1_1_fu_364_p1, "tmp_2_1_1_fu_364_p1");
    sc_trace(mVcdFile, tmp_2_1_2_fu_368_p1, "tmp_2_1_2_fu_368_p1");
    sc_trace(mVcdFile, tmp_2_1_3_fu_372_p1, "tmp_2_1_3_fu_372_p1");
    sc_trace(mVcdFile, tmp_2_2_fu_376_p1, "tmp_2_2_fu_376_p1");
    sc_trace(mVcdFile, tmp_2_2_1_fu_380_p1, "tmp_2_2_1_fu_380_p1");
    sc_trace(mVcdFile, tmp_2_2_2_fu_384_p1, "tmp_2_2_2_fu_384_p1");
    sc_trace(mVcdFile, tmp_2_2_3_fu_388_p1, "tmp_2_2_3_fu_388_p1");
    sc_trace(mVcdFile, tmp_2_3_fu_392_p1, "tmp_2_3_fu_392_p1");
    sc_trace(mVcdFile, tmp_2_3_1_fu_397_p1, "tmp_2_3_1_fu_397_p1");
    sc_trace(mVcdFile, tmp_2_3_2_fu_402_p1, "tmp_2_3_2_fu_402_p1");
    sc_trace(mVcdFile, tmp_2_3_3_fu_407_p1, "tmp_2_3_3_fu_407_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

substituteBytes::~substituteBytes() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sbox_V_U;
}

void substituteBytes::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        reg_324 = state_data_V_q0.read();
        reg_328 = state_data_V_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        reg_332 = state_data_V_q0.read();
        reg_336 = state_data_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_data_V_load_10_reg_512 = state_data_V_q0.read();
        state_data_V_load_11_reg_517 = state_data_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_data_V_load_4_reg_452 = state_data_V_q0.read();
        state_data_V_load_5_reg_457 = state_data_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        state_data_V_load_6_reg_472 = state_data_V_q0.read();
        state_data_V_load_7_reg_477 = state_data_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        state_data_V_load_8_reg_492 = state_data_V_q0.read();
        state_data_V_load_9_reg_497 = state_data_V_q1.read();
    }
}

void substituteBytes::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void substituteBytes::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void substituteBytes::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void substituteBytes::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void substituteBytes::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void substituteBytes::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void substituteBytes::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void substituteBytes::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void substituteBytes::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void substituteBytes::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void substituteBytes::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void substituteBytes::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void substituteBytes::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void substituteBytes::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void substituteBytes::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void substituteBytes::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void substituteBytes::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void substituteBytes::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void substituteBytes::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void substituteBytes::thread_sbox_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        sbox_V_address0 =  (sc_lv<8>) (tmp_2_3_2_fu_402_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        sbox_V_address0 =  (sc_lv<8>) (tmp_2_3_fu_392_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        sbox_V_address0 =  (sc_lv<8>) (tmp_2_2_2_fu_384_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        sbox_V_address0 =  (sc_lv<8>) (tmp_2_2_fu_376_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        sbox_V_address0 =  (sc_lv<8>) (tmp_2_1_2_fu_368_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        sbox_V_address0 =  (sc_lv<8>) (tmp_2_1_fu_360_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        sbox_V_address0 =  (sc_lv<8>) (tmp_2_0_2_fu_350_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sbox_V_address0 =  (sc_lv<8>) (tmp_2_fu_340_p1.read());
    } else {
        sbox_V_address0 = "XXXXXXXX";
    }
}

void substituteBytes::thread_sbox_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        sbox_V_address1 =  (sc_lv<8>) (tmp_2_3_3_fu_407_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        sbox_V_address1 =  (sc_lv<8>) (tmp_2_3_1_fu_397_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        sbox_V_address1 =  (sc_lv<8>) (tmp_2_2_3_fu_388_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        sbox_V_address1 =  (sc_lv<8>) (tmp_2_2_1_fu_380_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        sbox_V_address1 =  (sc_lv<8>) (tmp_2_1_3_fu_372_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        sbox_V_address1 =  (sc_lv<8>) (tmp_2_1_1_fu_364_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        sbox_V_address1 =  (sc_lv<8>) (tmp_2_0_3_fu_355_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sbox_V_address1 =  (sc_lv<8>) (tmp_2_0_1_fu_345_p1.read());
    } else {
        sbox_V_address1 = "XXXXXXXX";
    }
}

void substituteBytes::thread_sbox_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        sbox_V_ce0 = ap_const_logic_1;
    } else {
        sbox_V_ce0 = ap_const_logic_0;
    }
}

void substituteBytes::thread_sbox_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        sbox_V_ce1 = ap_const_logic_1;
    } else {
        sbox_V_ce1 = ap_const_logic_0;
    }
}

void substituteBytes::thread_state_data_V_addr_10_reg_482() {
    state_data_V_addr_10_reg_482 =  (sc_lv<4>) (ap_const_lv64_A);
}

void substituteBytes::thread_state_data_V_addr_11_reg_487() {
    state_data_V_addr_11_reg_487 =  (sc_lv<4>) (ap_const_lv64_B);
}

void substituteBytes::thread_state_data_V_addr_12_reg_502() {
    state_data_V_addr_12_reg_502 =  (sc_lv<4>) (ap_const_lv64_C);
}

void substituteBytes::thread_state_data_V_addr_13_reg_507() {
    state_data_V_addr_13_reg_507 =  (sc_lv<4>) (ap_const_lv64_D);
}

void substituteBytes::thread_state_data_V_addr_14_reg_522() {
    state_data_V_addr_14_reg_522 =  (sc_lv<4>) (ap_const_lv64_E);
}

void substituteBytes::thread_state_data_V_addr_15_reg_527() {
    state_data_V_addr_15_reg_527 =  (sc_lv<4>) (ap_const_lv64_F);
}

void substituteBytes::thread_state_data_V_addr_1_reg_417() {
    state_data_V_addr_1_reg_417 =  (sc_lv<4>) (ap_const_lv64_1);
}

void substituteBytes::thread_state_data_V_addr_2_reg_422() {
    state_data_V_addr_2_reg_422 =  (sc_lv<4>) (ap_const_lv64_2);
}

void substituteBytes::thread_state_data_V_addr_3_reg_427() {
    state_data_V_addr_3_reg_427 =  (sc_lv<4>) (ap_const_lv64_3);
}

void substituteBytes::thread_state_data_V_addr_4_reg_432() {
    state_data_V_addr_4_reg_432 =  (sc_lv<4>) (ap_const_lv64_4);
}

void substituteBytes::thread_state_data_V_addr_5_reg_437() {
    state_data_V_addr_5_reg_437 =  (sc_lv<4>) (ap_const_lv64_5);
}

void substituteBytes::thread_state_data_V_addr_6_reg_442() {
    state_data_V_addr_6_reg_442 =  (sc_lv<4>) (ap_const_lv64_6);
}

void substituteBytes::thread_state_data_V_addr_7_reg_447() {
    state_data_V_addr_7_reg_447 =  (sc_lv<4>) (ap_const_lv64_7);
}

void substituteBytes::thread_state_data_V_addr_8_reg_462() {
    state_data_V_addr_8_reg_462 =  (sc_lv<4>) (ap_const_lv64_8);
}

void substituteBytes::thread_state_data_V_addr_9_reg_467() {
    state_data_V_addr_9_reg_467 =  (sc_lv<4>) (ap_const_lv64_9);
}

void substituteBytes::thread_state_data_V_addr_reg_412() {
    state_data_V_addr_reg_412 =  (sc_lv<4>) (ap_const_lv64_0);
}

void substituteBytes::thread_state_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        state_data_V_address0 = state_data_V_addr_14_reg_522.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        state_data_V_address0 = state_data_V_addr_12_reg_502.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_data_V_address0 = state_data_V_addr_10_reg_482.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        state_data_V_address0 = state_data_V_addr_8_reg_462.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        state_data_V_address0 = state_data_V_addr_6_reg_442.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        state_data_V_address0 = state_data_V_addr_4_reg_432.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        state_data_V_address0 = state_data_V_addr_2_reg_422.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        state_data_V_address0 = state_data_V_addr_reg_412.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_E);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_C);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_A);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        state_data_V_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        state_data_V_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void substituteBytes::thread_state_data_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        state_data_V_address1 = state_data_V_addr_15_reg_527.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        state_data_V_address1 = state_data_V_addr_13_reg_507.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_data_V_address1 = state_data_V_addr_11_reg_487.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        state_data_V_address1 = state_data_V_addr_9_reg_467.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        state_data_V_address1 = state_data_V_addr_7_reg_447.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        state_data_V_address1 = state_data_V_addr_5_reg_437.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        state_data_V_address1 = state_data_V_addr_3_reg_427.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        state_data_V_address1 = state_data_V_addr_1_reg_417.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_F);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_D);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_9);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        state_data_V_address1 =  (sc_lv<4>) (ap_const_lv64_1);
    } else {
        state_data_V_address1 =  (sc_lv<4>) ("XXXX");
    }
}

void substituteBytes::thread_state_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        state_data_V_ce0 = ap_const_logic_1;
    } else {
        state_data_V_ce0 = ap_const_logic_0;
    }
}

void substituteBytes::thread_state_data_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        state_data_V_ce1 = ap_const_logic_1;
    } else {
        state_data_V_ce1 = ap_const_logic_0;
    }
}

void substituteBytes::thread_state_data_V_d0() {
    state_data_V_d0 = sbox_V_q0.read();
}

void substituteBytes::thread_state_data_V_d1() {
    state_data_V_d1 = sbox_V_q1.read();
}

void substituteBytes::thread_state_data_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        state_data_V_we0 = ap_const_logic_1;
    } else {
        state_data_V_we0 = ap_const_logic_0;
    }
}

void substituteBytes::thread_state_data_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        state_data_V_we1 = ap_const_logic_1;
    } else {
        state_data_V_we1 = ap_const_logic_0;
    }
}

void substituteBytes::thread_tmp_2_0_1_fu_345_p1() {
    tmp_2_0_1_fu_345_p1 = esl_zext<64,8>(reg_328.read());
}

void substituteBytes::thread_tmp_2_0_2_fu_350_p1() {
    tmp_2_0_2_fu_350_p1 = esl_zext<64,8>(reg_332.read());
}

void substituteBytes::thread_tmp_2_0_3_fu_355_p1() {
    tmp_2_0_3_fu_355_p1 = esl_zext<64,8>(reg_336.read());
}

void substituteBytes::thread_tmp_2_1_1_fu_364_p1() {
    tmp_2_1_1_fu_364_p1 = esl_zext<64,8>(state_data_V_load_5_reg_457.read());
}

void substituteBytes::thread_tmp_2_1_2_fu_368_p1() {
    tmp_2_1_2_fu_368_p1 = esl_zext<64,8>(state_data_V_load_6_reg_472.read());
}

void substituteBytes::thread_tmp_2_1_3_fu_372_p1() {
    tmp_2_1_3_fu_372_p1 = esl_zext<64,8>(state_data_V_load_7_reg_477.read());
}

void substituteBytes::thread_tmp_2_1_fu_360_p1() {
    tmp_2_1_fu_360_p1 = esl_zext<64,8>(state_data_V_load_4_reg_452.read());
}

void substituteBytes::thread_tmp_2_2_1_fu_380_p1() {
    tmp_2_2_1_fu_380_p1 = esl_zext<64,8>(state_data_V_load_9_reg_497.read());
}

void substituteBytes::thread_tmp_2_2_2_fu_384_p1() {
    tmp_2_2_2_fu_384_p1 = esl_zext<64,8>(state_data_V_load_10_reg_512.read());
}

void substituteBytes::thread_tmp_2_2_3_fu_388_p1() {
    tmp_2_2_3_fu_388_p1 = esl_zext<64,8>(state_data_V_load_11_reg_517.read());
}

void substituteBytes::thread_tmp_2_2_fu_376_p1() {
    tmp_2_2_fu_376_p1 = esl_zext<64,8>(state_data_V_load_8_reg_492.read());
}

void substituteBytes::thread_tmp_2_3_1_fu_397_p1() {
    tmp_2_3_1_fu_397_p1 = esl_zext<64,8>(reg_328.read());
}

void substituteBytes::thread_tmp_2_3_2_fu_402_p1() {
    tmp_2_3_2_fu_402_p1 = esl_zext<64,8>(reg_332.read());
}

void substituteBytes::thread_tmp_2_3_3_fu_407_p1() {
    tmp_2_3_3_fu_407_p1 = esl_zext<64,8>(reg_336.read());
}

void substituteBytes::thread_tmp_2_3_fu_392_p1() {
    tmp_2_3_fu_392_p1 = esl_zext<64,8>(reg_324.read());
}

void substituteBytes::thread_tmp_2_fu_340_p1() {
    tmp_2_fu_340_p1 = esl_zext<64,8>(reg_324.read());
}

void substituteBytes::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
            break;
    }
}

}

