// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_AESEncrypt_TopFunction (
hls::stream<struct ap_axiu<128, 1, 1, 1 > > (&stream_in_text),
hls::stream<struct ap_axiu<128, 1, 1, 1 > > (&stream_in_key),
hls::stream<struct ap_axiu<128, 1, 1, 1 > > (&stream_out));
