
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaesencrypt_topfunction.h"

/*
* The configuration table for devices
*/

XAesencrypt_topfunction_Config XAesencrypt_topfunction_ConfigTable[XPAR_XAESENCRYPT_TOPFUNCTION_NUM_INSTANCES] =
{
	{
		XPAR_AESENCRYPT_TOPFUNCTI_0_DEVICE_ID,
		XPAR_AESENCRYPT_TOPFUNCTI_0_S_AXI_CONTROL_BASEADDR
	}
};


